
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - "master"
  - "develop"
  - "feat-github-actions"
  - name: "release-*"
    prerelease: "alpha"

plugins:
  - path: "@semantic-release/commit-analyzer"
  - path: "@semantic-release/release-notes-generator"
    commit: "-/commit"
  - path: "@semantic-release/github"
  - path: "@semantic-release/changelog"
    changelogFile: "CHANGELOG.md"
    changelogTitle: "# WP Basic Bootstrap changelog"
  - path: "@semantic-release/git"
    assets:
      - "CHANGELOG.md"
      - "style.css"
    message: |
      chore(release): ${nextRelease.version}

      ${nextRelease.notes}
  - path: "@semantic-release/exec"
    verifyReleaseCmd: "sed -i \"s/Version: .*/Version: ${nextRelease.version}/\" style.css"
  - path: "@saithodev/semantic-release-backmerge"
    backmergeBranches:
      - from: "master"
        to: "develop"
